# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52ce5573bd20214e6711b23c7a4ca7355009a8c0db923797d9f165a66be3ad310f58fb71f043db2fcbe97774318013c7dabdb76d539bd999e54f6eaf769a4995

test:
  secret_key_base: 546caaf2efb1c600bcc2bec641071654b8f6fba60b6ef104c8612699ad37ff95c85a63874ff5315109d791c1aafe09907aabf8d7ee68bb184604a6497e6e35bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
